services:
  xolotl:
    build: .
    image: xolotl:latest
    container_name: xolotl-service
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/services"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
